<?php

/*
 * PUQcloud - Free Cloud Billing System
 * Main billing system core logic
 *
 * Copyright (C) 2025 PUQ sp. z o.o.
 * Licensed under GNU GPLv3
 * https://www.gnu.org/licenses/gpl-3.0.html
 *
 * Author: Dmytro Kravchenko <dmytro.kravchenko@ihostmi.com>
 * Website: https://puqcloud.com
 * E-mail: support@puqcloud.com
 *
 * Do not remove this header.
 */

namespace Database\Factories;

use App\Models\ProductOptionGroup;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

class ProductOptionGroupFactory extends Factory
{
    protected $model = ProductOptionGroup::class;

    public function definition(): array
    {
        $types = [
            'RAM' => 'dropdown',
            'CPU' => 'dropdown',
            'Disk' => 'dropdown',
            'OS' => 'dropdown',
            'Location' => 'dropdown',
            'GPU' => 'dropdown',
            'Firewall' => 'checkbox',
            'Backup' => 'dropdown',
            'Bandwidth' => 'dropdown',
            'Support' => 'dropdown',
        ];

        $key = $this->faker->randomElement(array_keys($types));
        $type = $types[$key];

        return [
            'uuid' => Str::uuid(),
            'key' => $key,
            'type' => $type,
            'hidden' => $this->faker->boolean(5), // 5% chance to be hidden
            'notes' => 'Generated by ProductOptionGroupFactory',
        ];
    }

    public function withType(string $key): self
    {
        $types = [
            'RAM' => 'dropdown',
            'CPU' => 'dropdown',
            'Disk' => 'dropdown',
            'OS' => 'dropdown',
            'Location' => 'dropdown',
            'GPU' => 'dropdown',
            'Firewall' => 'checkbox',
            'Backup' => 'dropdown',
            'Bandwidth' => 'dropdown',
            'Support' => 'dropdown',
        ];

        return $this->state(function (array $attributes) use ($key, $types) {
            return [
                'key' => $key,
                'type' => $types[$key] ?? 'dropdown',
            ];
        });
    }

    public function withTranslations(): self
    {
        return $this->afterCreating(function (ProductOptionGroup $optionGroup) {
            $optionData = $this->generateOptionGroupData($optionGroup->key);

            $optionGroup->name = $optionData['name'];
            $optionGroup->short_description = $optionData['short_description'];
            $optionGroup->description = $optionData['description'];
            $optionGroup->save();
        });
    }

    private function generateOptionGroupData(string $key): array
    {
        $optionTemplates = [
            'RAM' => [
                'name' => 'Memory (RAM)',
                'short_description' => 'System memory allocation',
                'description' => 'Choose the amount of RAM memory for your service. More memory allows for better performance and handling of concurrent processes.',
            ],
            'CPU' => [
                'name' => 'CPU Cores',
                'short_description' => 'Processor cores',
                'description' => 'Select the number of CPU cores for your service. More cores provide better performance for multi-threaded applications.',
            ],
            'Disk' => [
                'name' => 'Storage Space',
                'short_description' => 'Disk storage capacity',
                'description' => 'Choose the amount of disk space for your files, applications, and data storage needs.',
            ],
            'OS' => [
                'name' => 'Operating System',
                'short_description' => 'Server operating system',
                'description' => 'Select the operating system that will be installed on your server. Different OS options provide different features and compatibility.',
            ],
            'Location' => [
                'name' => 'Data Center Location',
                'short_description' => 'Server location',
                'description' => 'Choose the geographic location of your server. Closer locations typically provide better latency for your users.',
            ],
            'GPU' => [
                'name' => 'Graphics Processing Unit',
                'short_description' => 'GPU acceleration',
                'description' => 'Add GPU acceleration for compute-intensive tasks like machine learning, rendering, or scientific computing.',
            ],
            'Firewall' => [
                'name' => 'Firewall Protection',
                'short_description' => 'Network security',
                'description' => 'Enable advanced firewall protection to secure your server against unauthorized access and malicious traffic.',
            ],
            'Backup' => [
                'name' => 'Backup Service',
                'short_description' => 'Data backup options',
                'description' => 'Choose backup frequency and retention options to protect your data against loss or corruption.',
            ],
            'Bandwidth' => [
                'name' => 'Network Bandwidth',
                'short_description' => 'Network speed',
                'description' => 'Select the network bandwidth allocation for your service, affecting data transfer speeds and capacity.',
            ],
            'Support' => [
                'name' => 'Support Level',
                'short_description' => 'Technical support tier',
                'description' => 'Choose your support level for different response times and support channel access.',
            ],
        ];

        return $optionTemplates[$key] ?? [
            'name' => ucwords($key),
            'short_description' => 'Service option',
            'description' => 'Additional service configuration option for your product.',
        ];
    }
}
