<label class="form-label" for="icon">{{ __('main.Icon') }}</label>
<div class="input-group">
    <span
        class="input-group-text p-0 text-center"
        id="iconSelected"
        style="width: 50px; display: flex; align-items: center; justify-content: center;">
        <div id="iconPreview" class="text-center"></div>
    </span>
    <input type="text" class="form-control" id="icon" name="icon">
    <button class="btn btn-outline-secondary" type="button" id="openIconPicker">
        {{ __('main.Pick') }}
    </button>
</div>

@section('js')
    @parent
    <script>
        const $iconInput = $('#icon');
        const $iconPreview = $('#iconPreview');
        let lastIconClass = '';

        setInterval(() => {
            const currentIconClass = $iconInput.val();
            if (currentIconClass !== lastIconClass) {
                if (currentIconClass.startsWith('flag')) {
                    $iconPreview.html(`<div class="${currentIconClass}" style="width: 32px;"></div>`);
                } else {
                    $iconPreview.html(`<i class="${currentIconClass}"></i>`);
                }
                lastIconClass = currentIconClass;
            }
        }, 100);

        $('#openIconPicker').on('click', function () {
            const iconSets = {
                'Flags': [
                    'fi fi-ad', 'fi fi-ae', 'fi fi-af', 'fi fi-ag', 'fi fi-ai', 'fi fi-al', 'fi fi-am', 'fi fi-ao', 'fi fi-ar', 'fi fi-as',
                    'fi fi-at', 'fi fi-au', 'fi fi-aw', 'fi fi-ax', 'fi fi-az', 'fi fi-ba', 'fi fi-bb', 'fi fi-bd', 'fi fi-be', 'fi fi-bf',
                    'fi fi-bg', 'fi fi-bh', 'fi fi-bi', 'fi fi-bj', 'fi fi-bl', 'fi fi-bm', 'fi fi-bn', 'fi fi-bo', 'fi fi-br', 'fi fi-bs',
                    'fi fi-bt', 'fi fi-bv', 'fi fi-bw', 'fi fi-by', 'fi fi-bz', 'fi fi-ca', 'fi fi-cc', 'fi fi-cd', 'fi fi-cf', 'fi fi-cg',
                    'fi fi-ch', 'fi fi-ci', 'fi fi-ck', 'fi fi-cl', 'fi fi-cm', 'fi fi-cn', 'fi fi-co', 'fi fi-cr', 'fi fi-cu', 'fi fi-cv',
                    'fi fi-cw', 'fi fi-cx', 'fi fi-cy', 'fi fi-cz', 'fi fi-de', 'fi fi-dj', 'fi fi-dk', 'fi fi-dm', 'fi fi-do', 'fi fi-dz',
                    'fi fi-ec', 'fi fi-ee', 'fi fi-eg', 'fi fi-er', 'fi fi-es', 'fi fi-et', 'fi fi-eu', 'fi fi-fi', 'fi fi-fj', 'fi fi-fk',
                    'fi fi-fm', 'fi fi-fo', 'fi fi-fr', 'fi fi-ga', 'fi fi-gb', 'fi fi-gd', 'fi fi-ge', 'fi fi-gf', 'fi fi-gg', 'fi fi-gh',
                    'fi fi-gi', 'fi fi-gl', 'fi fi-gm', 'fi fi-gn', 'fi fi-gp', 'fi fi-gq', 'fi fi-gr', 'fi fi-gs', 'fi fi-gt', 'fi fi-gu',
                    'fi fi-gw', 'fi fi-gy', 'fi fi-hk', 'fi fi-hm', 'fi fi-hn', 'fi fi-hr', 'fi fi-ht', 'fi fi-hu', 'fi fi-id', 'fi fi-ie',
                    'fi fi-il', 'fi fi-im', 'fi fi-in', 'fi fi-io', 'fi fi-iq', 'fi fi-ir', 'fi fi-is', 'fi fi-it', 'fi fi-je', 'fi fi-jm',
                    'fi fi-jo', 'fi fi-jp', 'fi fi-ke', 'fi fi-kg', 'fi fi-kh', 'fi fi-ki', 'fi fi-km', 'fi fi-kn', 'fi fi-kp', 'fi fi-kr',
                    'fi fi-kw', 'fi fi-ky', 'fi fi-kz', 'fi fi-la', 'fi fi-lb', 'fi fi-lc', 'fi fi-li', 'fi fi-lk', 'fi fi-lr', 'fi fi-ls',
                    'fi fi-lt', 'fi fi-lu', 'fi fi-lv', 'fi fi-ly', 'fi fi-ma', 'fi fi-mc', 'fi fi-md', 'fi fi-me', 'fi fi-mf', 'fi fi-mg',
                    'fi fi-mh', 'fi fi-mk', 'fi fi-ml', 'fi fi-mm', 'fi fi-mn', 'fi fi-mo', 'fi fi-mp', 'fi fi-mq', 'fi fi-mr', 'fi fi-ms',
                    'fi fi-mt', 'fi fi-mu', 'fi fi-mv', 'fi fi-mw', 'fi fi-mx', 'fi fi-my', 'fi fi-mz', 'fi fi-na', 'fi fi-nc', 'fi fi-ne',
                    'fi fi-nf', 'fi fi-ng', 'fi fi-ni', 'fi fi-nl', 'fi fi-no', 'fi fi-np', 'fi fi-nr', 'fi fi-nu', 'fi fi-nz', 'fi fi-om',
                    'fi fi-pa', 'fi fi-pe', 'fi fi-pf', 'fi fi-pg', 'fi fi-ph', 'fi fi-pk', 'fi fi-pl', 'fi fi-pm', 'fi fi-pn', 'fi fi-pr',
                    'fi fi-ps', 'fi fi-pt', 'fi fi-pw', 'fi fi-py', 'fi fi-qa', 'fi fi-re', 'fi fi-ro', 'fi fi-rs', 'fi fi-ru', 'fi fi-rw',
                    'fi fi-sa', 'fi fi-sb', 'fi fi-sc', 'fi fi-sd', 'fi fi-se', 'fi fi-sg', 'fi fi-sh', 'fi fi-si', 'fi fi-sj', 'fi fi-sk',
                    'fi fi-sl', 'fi fi-sm', 'fi fi-sn', 'fi fi-so', 'fi fi-sr', 'fi fi-ss', 'fi fi-st', 'fi fi-sv', 'fi fi-sx', 'fi fi-sy',
                    'fi fi-sz', 'fi fi-tc', 'fi fi-td', 'fi fi-tf', 'fi fi-tg', 'fi fi-th', 'fi fi-tj', 'fi fi-tk', 'fi fi-tl', 'fi fi-tm',
                    'fi fi-tn', 'fi fi-to', 'fi fi-tr', 'fi fi-tt', 'fi fi-tv', 'fi fi-tw', 'fi fi-tz', 'fi fi-ua', 'fi fi-ug', 'fi fi-um',
                    'fi fi-us', 'fi fi-uy', 'fi fi-uz', 'fi fi-va', 'fi fi-vc', 'fi fi-ve', 'fi fi-vg', 'fi fi-vi', 'fi fi-vn', 'fi fi-vu',
                    'fi fi-wf', 'fi fi-ws', 'fi fi-xk', 'fi fi-ye', 'fi fi-yt', 'fi fi-za', 'fi fi-zm', 'fi fi-zw'
                ],

                'FontAwesome': ['fa fa-address-book',
                    'fa fa-address-card',
                    'fa fa-adjust',
                    'fa fa-align-center',
                    'fa fa-align-justify',
                    'fa fa-align-left',
                    'fa fa-align-right',
                    'fa fa-ambulance',
                    'fa fa-american-sign-language-interpreting',
                    'fa fa-anchor',
                    'fa fa-angle-double-down',
                    'fa fa-angle-double-left',
                    'fa fa-angle-double-right',
                    'fa fa-angle-double-up',
                    'fa fa-angle-down',
                    'fa fa-angle-left',
                    'fa fa-angle-right',
                    'fa fa-angle-up',
                    'fa fa-archive',
                    'fa fa-arrow-circle-down',
                    'fa fa-arrow-circle-left',
                    'fa fa-arrow-circle-right',
                    'fa fa-arrow-circle-up',
                    'fa fa-arrow-down',
                    'fa fa-arrow-left',
                    'fa fa-arrow-right',
                    'fa fa-arrow-up',
                    'fa fa-arrows-alt',
                    'fa fa-assistive-listening-systems',
                    'fa fa-asterisk',
                    'fa fa-at',
                    'fa fa-audio-description',
                    'fa fa-backward',
                    'fa fa-balance-scale',
                    'fa fa-ban',
                    'fa fa-barcode',
                    'fa fa-bars',
                    'fa fa-battery-empty',
                    'fa fa-battery-full',
                    'fa fa-battery-half',
                    'fa fa-battery-quarter',
                    'fa fa-battery-three-quarters',
                    'fa fa-bed',
                    'fa fa-beer',
                    'fa fa-bell',
                    'fa fa-bell-slash',
                    'fa fa-bicycle',
                    'fa fa-binoculars',
                    'fa fa-birthday-cake',
                    'fa fa-blind',
                    'fa fa-bold',
                    'fa fa-bolt',
                    'fa fa-bomb',
                    'fa fa-book',
                    'fa fa-bookmark',
                    'fa fa-braille',
                    'fa fa-briefcase',
                    'fa fa-bug',
                    'fa fa-building',
                    'fa fa-bullhorn',
                    'fa fa-bullseye',
                    'fa fa-bus',
                    'fa fa-cab',
                    'fa fa-calculator',
                    'fa fa-calendar',
                    'fa fa-calendar-o',
                    'fa fa-calendar-plus-o',
                    'fa fa-calendar-times-o',
                    'fa fa-camera',
                    'fa fa-camera-retro',
                    'fa fa-car',
                    'fa fa-caret-down',
                    'fa fa-caret-left',
                    'fa fa-caret-right',
                    'fa fa-caret-square-o-down',
                    'fa fa-caret-square-o-left',
                    'fa fa-caret-square-o-right',
                    'fa fa-caret-square-o-up',
                    'fa fa-caret-up',
                    'fa fa-cart-arrow-down',
                    'fa fa-cart-plus',
                    'fa fa-cc',
                    'fa fa-certificate',
                    'fa fa-chain-broken',
                    'fa fa-check',
                    'fa fa-check-circle',
                    'fa fa-check-square',
                    'fa fa-chevron-circle-down',
                    'fa fa-chevron-circle-left',
                    'fa fa-chevron-circle-right',
                    'fa fa-chevron-circle-up',
                    'fa fa-chevron-down',
                    'fa fa-chevron-left',
                    'fa fa-chevron-right',
                    'fa fa-chevron-up',
                    'fa fa-child',
                    'fa fa-circle',
                    'fa fa-clipboard',
                    'fa fa-clock-o',
                    'fa fa-clone',
                    'fa fa-cloud',
                    'fa fa-times',
                    'fa fa-code',
                    'fa fa-code-fork',
                    'fa fa-coffee',
                    'fa fa-cog',
                    'fa fa-cogs',
                    'fa fa-columns',
                    'fa fa-comment',
                    'fa fa-commenting',
                    'fa fa-comments',
                    'fa fa-compass',
                    'fa fa-compress',
                    'fa fa-copy',
                    'fa fa-copyright',
                    'fa fa-credit-card',
                    'fa fa-crop',
                    'fa fa-crosshairs',
                    'fa fa-cube',
                    'fa fa-cubes',
                    'fa fa-cut',
                    'fa fa-database',
                    'fa fa-deaf',
                    'fa fa-desktop',
                    'fa fa-dot-circle-o',
                    'fa fa-download',
                    'fa fa-drivers-license',
                    'fa fa-edit',
                    'fa fa-eject',
                    'fa fa-ellipsis-h',
                    'fa fa-ellipsis-v',
                    'fa fa-envelope',
                    'fa fa-envelope-open',
                    'fa fa-envelope-square',
                    'fa fa-eraser',
                    'fa fa-eur',
                    'fa fa-exclamation',
                    'fa fa-exclamation-circle',
                    'fa fa-exclamation-triangle',
                    'fa fa-expand',
                    'fa fa-eye',
                    'fa fa-eye-slash',
                    'fa fa-eyedropper',
                    'fa fa-fast-backward',
                    'fa fa-fast-forward',
                    'fa fa-fax',
                    'fa fa-female',
                    'fa fa-fighter-jet',
                    'fa fa-file',
                    'fa fa-file-archive-o',
                    'fa fa-file-audio-o',
                    'fa fa-file-code-o',
                    'fa fa-file-excel-o',
                    'fa fa-file-image-o',
                    'fa fa-file-pdf-o',
                    'fa fa-file-powerpoint-o',
                    'fa fa-file-sound-o',
                    'fa fa-file-text',
                    'fa fa-file-video-o',
                    'fa fa-file-word-o',
                    'fa fa-files-o',
                    'fa fa-film',
                    'fa fa-filter',
                    'fa fa-fire',
                    'fa fa-fire-extinguisher',
                    'fa fa-firefox',
                    'fa fa-first-order',
                    'fa fa-flag',
                    'fa fa-flag-checkered',
                    'fa fa-flask',
                    'fa fa-floppy-o',
                    'fa fa-folder',
                    'fa fa-folder-o',
                    'fa fa-folder-open',
                    'fa fa-folder-open-o',
                    'fa fa-font',
                    'fa fa-font-awesome',
                    'fa fa-fonticons',
                    'fa fa-fort-awesome',
                    'fa fa-forumbee',
                    'fa fa-forward',
                    'fa fa-foursquare',
                    'fa fa-free-code-camp',
                    'fa fa-frown-o',
                    'fa fa-futbol-o',
                    'fa fa-gamepad',
                    'fa fa-gavel',
                    'fa fa-gbp',
                    'fa fa-genderless',
                    'fa fa-get-pocket',
                    'fa fa-gg',
                    'fa fa-gg-circle',
                    'fa fa-gift',
                    'fa fa-git',
                    'fa fa-git-square',
                    'fa fa-github',
                    'fa fa-github-alt',
                    'fa fa-github-square',
                    'fa fa-gitlab',
                    'fa fa-glass',
                    'fa fa-glide',
                    'fa fa-glide-g',
                    'fa fa-globe',
                    'fa fa-google',
                    'fa fa-google-plus',
                    'fa fa-google-plus-official',
                    'fa fa-google-plus-square',
                    'fa fa-google-wallet',
                    'fa fa-graduation-cap',
                    'fa fa-gratipay',
                    'fa fa-grav',
                    'fa fa-h-square',
                    'fa fa-hacker-news',
                    'fa fa-hand-lizard-o',
                    'fa fa-hand-o-down',
                    'fa fa-hand-o-left',
                    'fa fa-hand-o-right',
                    'fa fa-hand-o-up',
                    'fa fa-hand-paper-o',
                    'fa fa-hand-peace-o',
                    'fa fa-hand-pointer-o',
                    'fa fa-hand-rock-o',
                    'fa fa-hand-scissors-o',
                    'fa fa-hand-spock-o',
                    'fa fa-handshake-o',
                    'fa fa-hashtag',
                    'fa fa-hdd-o',
                    'fa fa-header',
                    'fa fa-headphones',
                    'fa fa-heart',
                    'fa fa-heart-o',
                    'fa fa-heartbeat',
                    'fa fa-history',
                    'fa fa-home',
                    'fa fa-hospital-o',
                    'fa fa-hourglass',
                    'fa fa-hourglass-end',
                    'fa fa-hourglass-half',
                    'fa fa-hourglass-o',
                    'fa fa-hourglass-start',
                    'fa fa-i-cursor',
                    'fa fa-id-badge',
                    'fa fa-id-card',
                    'fa fa-id-card-o',
                    'fa fa-ils',
                    'fa fa-inbox',
                    'fa fa-indent',
                    'fa fa-industry',
                    'fa fa-info',
                    'fa fa-info-circle',
                    'fa fa-inr',
                    'fa fa-instagram',
                    'fa fa-internet-explorer',
                    'fa fa-ioxhost',
                    'fa fa-italic',
                    'fa fa-joomla',
                    'fa fa-jpy',
                    'fa fa-jsfiddle',
                    'fa fa-key',
                    'fa fa-keyboard-o',
                    'fa fa-krw',
                    'fa fa-language',
                    'fa fa-laptop',
                    'fa fa-lastfm',
                    'fa fa-lastfm-square',
                    'fa fa-leaf',
                    'fa fa-leanpub',
                    'fa fa-lemon-o',
                    'fa fa-level-down',
                    'fa fa-level-up',
                    'fa fa-life-ring',
                    'fa fa-lightbulb-o',
                    'fa fa-line-chart',
                    'fa fa-link',
                    'fa fa-linkedin',
                    'fa fa-linkedin-square',
                    'fa fa-linode',
                    'fa fa-linux',
                    'fa fa-list',
                    'fa fa-list-alt',
                    'fa fa-list-ol',
                    'fa fa-list-ul',
                    'fa fa-location-arrow',
                    'fa fa-lock',
                    'fa fa-long-arrow-down',
                    'fa fa-long-arrow-left',
                    'fa fa-long-arrow-right',
                    'fa fa-long-arrow-up',
                    'fa fa-low-vision',
                    'fa fa-magic',
                    'fa fa-magnet',
                    'fa fa-male',
                    'fa fa-map',
                    'fa fa-map-marker',
                    'fa fa-map-o',
                    'fa fa-map-pin',
                    'fa fa-map-signs',
                    'fa fa-mars',
                    'fa fa-mars-double',
                    'fa fa-mars-stroke',
                    'fa fa-mars-stroke-h',
                    'fa fa-mars-stroke-v',
                    'fa fa-maxcdn',
                    'fa fa-meanpath',
                    'fa fa-medium',
                    'fa fa-medkit',
                    'fa fa-meh-o',
                    'fa fa-mercury',
                    'fa fa-microphone',
                    'fa fa-microphone-slash',
                    'fa fa-minus',
                    'fa fa-minus-circle',
                    'fa fa-minus-square',
                    'fa fa-minus-square-o',
                    'fa fa-mobile',
                    'fa fa-mobile-phone',
                    'fa fa-money',
                    'fa fa-moon-o',
                    'fa fa-mortar-board',
                    'fa fa-motorcycle',
                    'fa fa-mouse-pointer',
                    'fa fa-music',
                    'fa fa-navicon',
                    'fa fa-neuter',
                    'fa fa-newspaper-o',
                    'fa fa-object-group',
                    'fa fa-object-ungroup',
                    'fa fa-odnoklassniki',
                    'fa fa-odnoklassniki-square',
                    'fa fa-opencart',
                    'fa fa-openid',
                    'fa fa-opera',
                    'fa fa-optin-monster',
                    'fa fa-outdent',
                    'fa fa-pagelines',
                    'fa fa-paint-brush',
                    'fa fa-paper-plane',
                    'fa fa-paper-plane-o',
                    'fa fa-paperclip',
                    'fa fa-paragraph',
                    'fa fa-paste',
                    'fa fa-pause',
                    'fa fa-pause-circle',
                    'fa fa-pause-circle-o',
                    'fa fa-paw',
                    'fa fa-paypal',
                    'fa fa-pencil',
                    'fa fa-pencil-square',
                    'fa fa-pencil-square-o',
                    'fa fa-percent',
                    'fa fa-phone',
                    'fa fa-phone-square',
                    'fa fa-photo',
                    'fa fa-picture-o',
                    'fa fa-pie-chart',
                    'fa fa-plane',
                    'fa fa-play',
                    'fa fa-play-circle',
                    'fa fa-play-circle-o',
                    'fa fa-plug',
                    'fa fa-plus',
                    'fa fa-plus-circle',
                    'fa fa-plus-square',
                    'fa fa-plus-square-o',
                    'fa fa-power-off',
                    'fa fa-print',
                    'fa fa-product-hunt',
                    'fa fa-puzzle-piece',
                    'fa fa-qq',
                    'fa fa-qrcode',
                    'fa fa-question',
                    'fa fa-question-circle',
                    'fa fa-quote-left',
                    'fa fa-quote-right',
                    'fa fa-random',
                    'fa fa-recycle',
                    'fa fa-reddit',
                    'fa fa-reddit-alien',
                    'fa fa-reddit-square',
                    'fa fa-refresh',
                    'fa fa-registered',
                    'fa fa-remove',
                    'fa fa-renren',
                    'fa fa-reorder',
                    'fa fa-repeat',
                    'fa fa-reply',
                    'fa fa-reply-all',
                    'fa fa-retweet',
                    'fa fa-road',
                    'fa fa-rocket',
                    'fa fa-rss',
                    'fa fa-rss-square',
                    'fa fa-rub',
                    'fa fa-safari',
                    'fa fa-save',
                    'fa fa-scissors',
                    'fa fa-scribd',
                    'fa fa-search',
                    'fa fa-search-minus',
                    'fa fa-search-plus',
                    'fa fa-send',
                    'fa fa-send-o',
                    'fa fa-server',
                    'fa fa-share',
                    'fa fa-share-alt',
                    'fa fa-share-alt-square',
                    'fa fa-share-square',
                    'fa fa-share-square-o',
                    'fa fa-shield',
                    'fa fa-ship',
                    'fa fa-shirtsinbulk',
                    'fa fa-shopping-bag',
                    'fa fa-shopping-basket',
                    'fa fa-shopping-cart',
                    'fa fa-shower',
                    'fa fa-sign-in',
                    'fa fa-sign-language',
                    'fa fa-sign-out',
                    'fa fa-signal',
                    'fa fa-simplybuilt',
                    'fa fa-sitemap',
                    'fa fa-skyatlas',
                    'fa fa-skype',
                    'fa fa-slack',
                    'fa fa-sliders',
                    'fa fa-slideshare',
                    'fa fa-smile-o',
                    'fa fa-snapchat',
                    'fa fa-snapchat-ghost',
                    'fa fa-snapchat-square',
                    'fa fa-snowflake-o',
                    'fa fa-sort',
                    'fa fa-sort-alpha-asc',
                    'fa fa-sort-alpha-desc',
                    'fa fa-sort-amount-asc',
                    'fa fa-sort-amount-desc',
                    'fa fa-sort-asc',
                    'fa fa-sort-desc',
                    'fa fa-sort-down',
                    'fa fa-sort-numeric-asc',
                    'fa fa-sort-numeric-desc',
                    'fa fa-sort-up',
                    'fa fa-soundcloud',
                    'fa fa-space-shuttle',
                    'fa fa-spinner',
                    'fa fa-spoon',
                    'fa fa-spotify',
                    'fa fa-square',
                    'fa fa-square-o',
                    'fa fa-stack-exchange',
                    'fa fa-stack-overflow',
                    'fa fa-star',
                    'fa fa-star-half',
                    'fa fa-star-half-o',
                    'fa fa-star-o',
                    'fa fa-steam',
                    'fa fa-steam-square',
                    'fa fa-step-backward',
                    'fa fa-step-forward',
                    'fa fa-stethoscope',
                    'fa fa-stop',
                    'fa fa-stop-circle',
                    'fa fa-stop-circle-o',
                    'fa fa-street-view',
                    'fa fa-strikethrough',
                    'fa fa-stumbleupon',
                    'fa fa-stumbleupon-circle',
                    'fa fa-subscript',
                    'fa fa-subway',
                    'fa fa-suitcase',
                    'fa fa-sun-o',
                    'fa fa-superpowers',
                    'fa fa-superscript',
                    'fa fa-support',
                    'fa fa-table',
                    'fa fa-tablet',
                    'fa fa-tachometer',
                    'fa fa-tag',
                    'fa fa-tags',
                    'fa fa-tasks',
                    'fa fa-taxi',
                    'fa fa-television',
                    'fa fa-terminal',
                    'fa fa-text-height',
                    'fa fa-text-width',
                    'fa fa-th',
                    'fa fa-th-large',
                    'fa fa-th-list',
                    'fa fa-themeisle',
                    'fa fa-thermometer',
                    'fa fa-thermometer-0',
                    'fa fa-thermometer-1',
                    'fa fa-thermometer-2',
                    'fa fa-thermometer-3',
                    'fa fa-thermometer-4',
                    'fa fa-thermometer-empty',
                    'fa fa-thermometer-full',
                    'fa fa-thermometer-half',
                    'fa fa-thermometer-quarter',
                    'fa fa-thermometer-three-quarters',
                    'fa fa-thumb-tack',
                    'fa fa-thumbs-down',
                    'fa fa-thumbs-o-down',
                    'fa fa-thumbs-o-up',
                    'fa fa-thumbs-up',
                    'fa fa-ticket',
                    'fa fa-times-circle',
                    'fa fa-times-circle-o',
                    'fa fa-times-rectangle',
                    'fa fa-times-rectangle-o',
                    'fa fa-tint',
                    'fa fa-toggle-down',
                    'fa fa-toggle-left',
                    'fa fa-toggle-off',
                    'fa fa-toggle-on',
                    'fa fa-toggle-right',
                    'fa fa-toggle-up',
                    'fa fa-trademark',
                    'fa fa-train',
                    'fa fa-transgender',
                    'fa fa-transgender-alt',
                    'fa fa-trash',
                    'fa fa-trash-o',
                    'fa fa-tree',
                    'fa fa-trello',
                    'fa fa-tripadvisor',
                    'fa fa-trophy',
                    'fa fa-truck',
                    'fa fa-try',
                    'fa fa-tty',
                    'fa fa-tumblr',
                    'fa fa-tumblr-square',
                    'fa fa-twitch',
                    'fa fa-twitter',
                    'fa fa-twitter-square',
                    'fa fa-umbrella',
                    'fa fa-underline',
                    'fa fa-undo',
                    'fa fa-universal-access',
                    'fa fa-university',
                    'fa fa-unlink',
                    'fa fa-unlock',
                    'fa fa-unlock-alt',
                    'fa fa-upload',
                    'fa fa-usd',
                    'fa fa-user',
                    'fa fa-user-circle',
                    'fa fa-user-circle-o',
                    'fa fa-user-o',
                    'fa fa-user-plus',
                    'fa fa-user-secret',
                    'fa fa-user-times',
                    'fa fa-users',
                    'fa fa-venus',
                    'fa fa-venus-double',
                    'fa fa-venus-mars',
                    'fa fa-viacoin',
                    'fa fa-video-camera',
                    'fa fa-vimeo',
                    'fa fa-vimeo-square',
                    'fa fa-vine',
                    'fa fa-vk',
                    'fa fa-volume-control-phone',
                    'fa fa-volume-down',
                    'fa fa-volume-off',
                    'fa fa-volume-up',
                    'fa fa-warning',
                    'fa fa-wechat',
                    'fa fa-weibo',
                    'fa fa-weixin',
                    'fa fa-whatsapp',
                    'fa fa-wheelchair',
                    'fa fa-wheelchair-alt',
                    'fa fa-wifi',
                    'fa fa-wikipedia-w',
                    'fa fa-window-close',
                    'fa fa-window-close-o',
                    'fa fa-window-maximize',
                    'fa fa-window-minimize',
                    'fa fa-window-restore',
                    'fa fa-windows',
                    'fa fa-won',
                    'fa fa-wordpress',
                    'fa fa-wpbeginner',
                    'fa fa-wpexplorer',
                    'fa fa-wpforms',
                    'fa fa-wrench',
                    'fa fa-xing',
                    'fa fa-xing-square',
                    'fa fa-y-combinator',
                    'fa fa-yahoo',
                    'fa fa-yelp',
                    'fa fa-youtube',
                    'fa fa-youtube-play',
                    'fa fa-youtube-square',],
                'LinearIcons': ["lnr-apartment",
                    "lnr-pencil",
                    "lnr-magic-wand",
                    "lnr-drop",
                    "lnr-lighter",
                    "lnr-poop",
                    "lnr-sun",
                    "lnr-moon",
                    "lnr-cloud",
                    "lnr-cloud-upload",
                    "lnr-cloud-download",
                    "lnr-cloud-sync",
                    "lnr-cloud-check",
                    "lnr-database",
                    "lnr-lock",
                    "lnr-cog",
                    "lnr-trash",
                    "lnr-dice",
                    "lnr-heart",
                    "lnr-star",
                    "lnr-star-half",
                    "lnr-star-empty",
                    "lnr-flag",
                    "lnr-envelope",
                    "lnr-paperclip",
                    "lnr-inbox",
                    "lnr-eye",
                    "lnr-printer",
                    "lnr-file-empty",
                    "lnr-file-add",
                    "lnr-enter",
                    "lnr-exit",
                    "lnr-graduation-hat",
                    "lnr-license",
                    "lnr-music-note",
                    "lnr-film-play",
                    "lnr-camera-video",
                    "lnr-camera",
                    "lnr-picture",
                    "lnr-book",
                    "lnr-bookmark",
                    "lnr-user",
                    "lnr-users",
                    "lnr-shirt",
                    "lnr-store",
                    "lnr-cart",
                    "lnr-tag",
                    "lnr-phone-handset",
                    "lnr-phone",
                    "lnr-pushpin",
                    "lnr-map-marker",
                    "lnr-map",
                    "lnr-location",
                    "lnr-calendar-full",
                    "lnr-keyboard",
                    "lnr-spell-check",
                    "lnr-screen",
                    "lnr-smartphone",
                    "lnr-tablet",
                    "lnr-laptop",
                    "lnr-laptop-phone",
                    "lnr-power-switch",
                    "lnr-bubble",
                    "lnr-heart-pulse",
                    "lnr-construction",
                    "lnr-pie-chart",
                    "lnr-chart-bars",
                    "lnr-gift",
                    "lnr-diamond",
                    "lnr-linearicons",
                    "lnr-dinner",
                    "lnr-coffee-cup",
                    "lnr-leaf",
                    "lnr-paw",
                    "lnr-rocket",
                    "lnr-briefcase",
                    "lnr-bus",
                    "lnr-car",
                    "lnr-train",
                    "lnr-bicycle",
                    "lnr-wheelchair",
                    "lnr-select",
                    "lnr-earth",
                    "lnr-smile",
                    "lnr-sad",
                    "lnr-neutral",
                    "lnr-mustache",
                    "lnr-alarm",
                    "lnr-bullhorn",
                    "lnr-volume-high",
                    "lnr-volume-medium",
                    "lnr-volume-low",
                    "lnr-volume",
                    "lnr-mic",
                    "lnr-hourglass",
                    "lnr-undo",
                    "lnr-redo",
                    "lnr-sync",
                    "lnr-history",
                    "lnr-clock",
                    "lnr-download",
                    "lnr-upload",
                    "lnr-enter-down",
                    "lnr-exit-up",
                    "lnr-bug",
                    "lnr-code",
                    "lnr-link",
                    "lnr-unlink",
                    "lnr-thumbs-up",
                    "lnr-thumbs-down",
                    "lnr-magnifier",
                    "lnr-cross",
                    "lnr-menu",
                    "lnr-list",
                    "lnr-chevron-up",
                    "lnr-chevron-down",
                    "lnr-chevron-left",
                    "lnr-chevron-right",
                    "lnr-arrow-up",
                    "lnr-arrow-down",
                    "lnr-arrow-left",
                    "lnr-arrow-right",
                    "lnr-move",
                    "lnr-warning",
                    "lnr-question-circle",
                    "lnr-menu-circle",
                    "lnr-checkmark-circle",
                    "lnr-cross-circle",
                    "lnr-plus-circle",
                    "lnr-circle-minus",
                    "lnr-arrow-up-circle",
                    "lnr-arrow-down-circle",
                    "lnr-arrow-left-circle",
                    "lnr-arrow-right-circle",
                    "lnr-chevron-up-circle",
                    "lnr-chevron-down-circle",
                    "lnr-chevron-left-circle",
                    "lnr-chevron-right-circle",
                    "lnr-crop",
                    "lnr-frame-expand",
                    "lnr-frame-contract",
                    "lnr-layers",
                    "lnr-funnel",
                    "lnr-text-format",
                    "lnr-text-format-remove",
                    "lnr-text-size",
                    "lnr-bold",
                    "lnr-italic",
                    "lnr-underline",
                    "lnr-strikethrough",
                    "lnr-highlight",
                    "lnr-text-align-left",
                    "lnr-text-align-center",
                    "lnr-text-align-right",
                    "lnr-text-align-justify",
                    "lnr-line-spacing",
                    "lnr-indent-increase",
                    "lnr-indent-decrease",
                    "lnr-pilcrow",
                    "lnr-direction-ltr",
                    "lnr-direction-rtl",
                    "lnr-page-break",
                    "lnr-sort-alpha-asc",
                    "lnr-sort-amount-asc",
                    "lnr-hand",
                    "lnr-pointer-up",
                    "lnr-pointer-right",
                    "lnr-pointer-down",
                    "lnr-pointer-left",],
                'PeIcons': ['pe-7s-album',
                    'pe-7s-arc',
                    'pe-7s-back-2',
                    'pe-7s-bandaid',
                    'pe-7s-car',
                    'pe-7s-diamond',
                    'pe-7s-door-lock',
                    'pe-7s-eyedropper',
                    'pe-7s-female',
                    'pe-7s-gym',
                    'pe-7s-hammer',
                    'pe-7s-headphones',
                    'pe-7s-helm',
                    'pe-7s-hourglass',
                    'pe-7s-leaf',
                    'pe-7s-magic-wand',
                    'pe-7s-male',
                    'pe-7s-map-2',
                    'pe-7s-next-2',
                    'pe-7s-paint-bucket',
                    'pe-7s-pendrive',
                    'pe-7s-photo',
                    'pe-7s-piggy',
                    'pe-7s-plugin',
                    'pe-7s-refresh-2',
                    'pe-7s-rocket',
                    'pe-7s-settings',
                    'pe-7s-shield',
                    'pe-7s-smile',
                    'pe-7s-usb',
                    'pe-7s-vector',
                    'pe-7s-wine',
                    'pe-7s-cloud-upload',
                    'pe-7s-cash',
                    'pe-7s-close',
                    'pe-7s-bluetooth',
                    'pe-7s-cloud-download',
                    'pe-7s-way',
                    'pe-7s-close-circle',
                    'pe-7s-id',
                    'pe-7s-angle-up',
                    'pe-7s-wristwatch',
                    'pe-7s-angle-up-circle',
                    'pe-7s-world',
                    'pe-7s-angle-right',
                    'pe-7s-volume',
                    'pe-7s-angle-right-circle',
                    'pe-7s-users',
                    'pe-7s-angle-left',
                    'pe-7s-user-female',
                    'pe-7s-angle-left-circle',
                    'pe-7s-up-arrow',
                    'pe-7s-angle-down',
                    'pe-7s-switch',
                    'pe-7s-angle-down-circle',
                    'pe-7s-scissors',
                    'pe-7s-wallet',
                    'pe-7s-safe',
                    'pe-7s-volume2',
                    'pe-7s-volume1',
                    'pe-7s-voicemail',
                    'pe-7s-video',
                    'pe-7s-user',
                    'pe-7s-upload',
                    'pe-7s-unlock',
                    'pe-7s-umbrella',
                    'pe-7s-trash',
                    'pe-7s-tools',
                    'pe-7s-timer',
                    'pe-7s-ticket',
                    'pe-7s-target',
                    'pe-7s-sun',
                    'pe-7s-study',
                    'pe-7s-stopwatch',
                    'pe-7s-star',
                    'pe-7s-speaker',
                    'pe-7s-signal',
                    'pe-7s-shuffle',
                    'pe-7s-shopbag',
                    'pe-7s-share',
                    'pe-7s-server',
                    'pe-7s-search',
                    'pe-7s-film',
                    'pe-7s-science',
                    'pe-7s-disk',
                    'pe-7s-ribbon',
                    'pe-7s-repeat',
                    'pe-7s-refresh',
                    'pe-7s-add-user',
                    'pe-7s-refresh-cloud',
                    'pe-7s-paperclip',
                    'pe-7s-radio',
                    'pe-7s-note2',
                    'pe-7s-print',
                    'pe-7s-network',
                    'pe-7s-prev',
                    'pe-7s-mute',
                    'pe-7s-power',
                    'pe-7s-medal',
                    'pe-7s-portfolio',
                    'pe-7s-like2',
                    'pe-7s-plus',
                    'pe-7s-left-arrow',
                    'pe-7s-play',
                    'pe-7s-key',
                    'pe-7s-plane',
                    'pe-7s-joy',
                    'pe-7s-photo-gallery',
                    'pe-7s-pin',
                    'pe-7s-phone',
                    'pe-7s-plug',
                    'pe-7s-pen',
                    'pe-7s-right-arrow',
                    'pe-7s-paper-plane',
                    'pe-7s-delete-user',
                    'pe-7s-paint',
                    'pe-7s-bottom-arrow',
                    'pe-7s-notebook',
                    'pe-7s-note',
                    'pe-7s-next',
                    'pe-7s-news-paper',
                    'pe-7s-musiclist',
                    'pe-7s-music',
                    'pe-7s-mouse',
                    'pe-7s-more',
                    'pe-7s-moon',
                    'pe-7s-monitor',
                    'pe-7s-micro',
                    'pe-7s-menu',
                    'pe-7s-map',
                    'pe-7s-map-marker',
                    'pe-7s-mail',
                    'pe-7s-mail-open',
                    'pe-7s-mail-open-file',
                    'pe-7s-magnet',
                    'pe-7s-loop',
                    'pe-7s-look',
                    'pe-7s-lock',
                    'pe-7s-lintern',
                    'pe-7s-link',
                    'pe-7s-like',
                    'pe-7s-light',
                    'pe-7s-less',
                    'pe-7s-keypad',
                    'pe-7s-junk',
                    'pe-7s-info',
                    'pe-7s-home',
                    'pe-7s-help2',
                    'pe-7s-help1',
                    'pe-7s-graph3',
                    'pe-7s-graph2',
                    'pe-7s-graph1',
                    'pe-7s-graph',
                    'pe-7s-global',
                    'pe-7s-gleam',
                    'pe-7s-glasses',
                    'pe-7s-gift',
                    'pe-7s-folder',
                    'pe-7s-flag',
                    'pe-7s-filter',
                    'pe-7s-file',
                    'pe-7s-expand1',
                    'pe-7s-exapnd2',
                    'pe-7s-edit',
                    'pe-7s-drop',
                    'pe-7s-drawer',
                    'pe-7s-download',
                    'pe-7s-display2',
                    'pe-7s-display1',
                    'pe-7s-diskette',
                    'pe-7s-date',
                    'pe-7s-cup',
                    'pe-7s-culture',
                    'pe-7s-crop',
                    'pe-7s-credit',
                    'pe-7s-copy-file',
                    'pe-7s-config',
                    'pe-7s-compass',
                    'pe-7s-comment',
                    'pe-7s-coffee',
                    'pe-7s-cloud',
                    'pe-7s-clock',
                    'pe-7s-check',
                    'pe-7s-chat',
                    'pe-7s-cart',
                    'pe-7s-camera',
                    'pe-7s-call',
                    'pe-7s-calculator',
                    'pe-7s-browser',
                    'pe-7s-box2',
                    'pe-7s-box1',
                    'pe-7s-bookmarks',
                    'pe-7s-bicycle',
                    'pe-7s-bell',
                    'pe-7s-battery',
                    'pe-7s-ball',
                    'pe-7s-back',
                    'pe-7s-attention',
                    'pe-7s-anchor',
                    'pe-7s-albums',
                    'pe-7s-alarm',
                    'pe-7s-airplay'],
            };

            const $modalTitle = $('#universalModal .modal-title');
            const $modalBody = $('#universalModal .modal-body');
            $modalTitle.text(translate('Select Icon'));
            $('#modalSaveButton').hide();

            let tabs = `<ul class="nav nav-tabs" id="iconTabs" role="tablist">`;
            let tabContent = `<div class="tab-content mt-3">`;
            let first = true;

            for (const [type, icons] of Object.entries(iconSets)) {
                const tabId = `tab-${type.toLowerCase()}`;

                tabs += `
                <li class="nav-item" role="presentation">
                    <button class="nav-link ${first ? 'active' : ''}" id="${tabId}-tab" data-bs-toggle="tab" data-bs-target="#${tabId}" type="button" role="tab">${type}</button>
                </li>
            `;

                const iconHtml = icons.map(cls => {
                    if (cls.startsWith('flag')) {
                        return `<div class="${cls} large m-2 icon-choice" data-class="${cls}"></div>`;
                    }
                    return `<i class="${cls} m-2 icon-choice" data-class="${cls}" style="font-size:24px; cursor:pointer;"></i>`;
                }).join('');

                tabContent += `
                <div class="tab-pane fade ${first ? 'show active' : ''}" id="${tabId}" role="tabpanel">
                    <input type="text" class="form-control mb-2 icon-search" placeholder="Search icons...">
                    <div class="d-flex flex-wrap icon-container" style="max-height:400px; overflow-y:auto;">
                        ${iconHtml}
                    </div>
                </div>
            `;
                first = false;
            }

            tabs += `</ul>`;
            tabContent += `</div>`;

            $modalBody.html(tabs + tabContent);
            $('#universalModal').modal('show');

            $modalBody.find('.icon-search').on('input', function () {
                const $input = $(this);
                const query = $input.val().toLowerCase();
                const $icons = $input.closest('.tab-pane').find('.icon-choice');
                $icons.each(function () {
                    const cls = $(this).data('class').toLowerCase();
                    $(this).toggle(cls.includes(query));
                });
            });

            $modalBody.find('.icon-choice').on('click', function () {
                const iconClass = $(this).data('class');
                $iconInput.val(iconClass).trigger('input');
                $('#iconPreview').html(
                    iconClass.startsWith('flag')
                        ? `<div class="${iconClass}"></div>`
                        : `<i class="${iconClass}"></i>`
                );
                $('#universalModal').modal('hide');
                $('#modalSaveButton').show();
            });
        });
    </script>
@endsection
